// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQjT0QS6kHYc88fCAcKpb-YwMoL31R_cg',
    appId: '1:959300672732:web:d12142d9c1742a67796819',
    messagingSenderId: '959300672732',
    projectId: 'fio-developer',
    authDomain: 'fio-developer.firebaseapp.com',
    storageBucket: 'fio-developer.firebasestorage.app',
    measurementId: 'G-0HFT12L94V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6sXV7xqIoUx1nkJzpjZXT2enjYBDtZaM',
    appId: '1:959300672732:android:5ac667510cdaa301796819',
    messagingSenderId: '959300672732',
    projectId: 'fio-developer',
    storageBucket: 'fio-developer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhnUTLmKKSLGvxM33g-Kqce6-2n38jb6Y',
    appId: '1:959300672732:ios:1e62d78b9b885613796819',
    messagingSenderId: '959300672732',
    projectId: 'fio-developer',
    storageBucket: 'fio-developer.firebasestorage.app',
    iosBundleId: 'com.fiodev.fioDeveloper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhnUTLmKKSLGvxM33g-Kqce6-2n38jb6Y',
    appId: '1:959300672732:ios:1e62d78b9b885613796819',
    messagingSenderId: '959300672732',
    projectId: 'fio-developer',
    storageBucket: 'fio-developer.firebasestorage.app',
    iosBundleId: 'com.fiodev.fioDeveloper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQjT0QS6kHYc88fCAcKpb-YwMoL31R_cg',
    appId: '1:959300672732:web:1708d8b7bbf0a0dd796819',
    messagingSenderId: '959300672732',
    projectId: 'fio-developer',
    authDomain: 'fio-developer.firebaseapp.com',
    storageBucket: 'fio-developer.firebasestorage.app',
    measurementId: 'G-8W8RGZ01QK',
  );
}
